name: ReleaseKit-iOS
description: ReleaseKit-iOS action to archive an app, export an IPA, and upload to App Store Connect with asc.
author: vinceglb

inputs:
  workspace:
    description: Path to the .xcworkspace file or directory.
    required: true
  scheme:
    description: Xcode scheme to archive.
    required: true
  app_id:
    description: App Store Connect app ID.
    required: true
  bundle_id:
    description: Expected app bundle identifier.
    required: true
  asc_key_id:
    description: App Store Connect API key ID.
    required: true
  asc_issuer_id:
    description: App Store Connect API issuer ID.
    required: true
  asc_private_key_b64:
    description: Base64-encoded contents of the App Store Connect private key (.p8).
    required: true
  asc_team_id:
    description: Apple Developer Team ID used for signing and export.
    required: true
  configuration:
    description: Xcode build configuration.
    required: false
    default: Release
  archive_path:
    description: Output path for the generated .xcarchive.
    required: false
    default: ${{ runner.temp }}/archive/App.xcarchive
  export_path:
    description: Output directory for exported artifacts (.ipa).
    required: false
    default: ${{ runner.temp }}/export
  asc_version:
    description: "asc CLI version to install (default: latest)."
    required: false
    default: latest
  wait_for_processing:
    description: Wait for App Store Connect build processing before returning.
    required: false
    default: "false"
  poll_interval:
    description: Poll interval for asc wait mode (for example 30s).
    required: false
    default: 30s
  xcodebuild_extra_args:
    description: Additional args appended to xcodebuild archive command.
    required: false
    default: ""

outputs:
  archive_path:
    description: Absolute path to generated .xcarchive.
    value: ${{ steps.run.outputs.archive_path }}
  ipa_path:
    description: Absolute path to generated .ipa.
    value: ${{ steps.run.outputs.ipa_path }}
  upload_id:
    description: App Store Connect build upload ID returned by asc.
    value: ${{ steps.run.outputs.upload_id }}
  file_id:
    description: App Store Connect build upload file ID returned by asc.
    value: ${{ steps.run.outputs.file_id }}
  asc_result_json:
    description: Compact JSON response from asc builds upload.
    value: ${{ steps.run.outputs.asc_result_json }}

runs:
  using: composite
  steps:
    - name: Install asc CLI
      shell: bash
      run: ${{ github.action_path }}/scripts/install-asc.sh
      env:
        INPUT_ASC_VERSION: ${{ inputs.asc_version }}

    - name: ReleaseKit-iOS archive, export, and upload
      id: run
      shell: bash
      run: ${{ github.action_path }}/scripts/run.sh
      env:
        INPUT_WORKSPACE: ${{ inputs.workspace }}
        INPUT_SCHEME: ${{ inputs.scheme }}
        INPUT_APP_ID: ${{ inputs.app_id }}
        INPUT_BUNDLE_ID: ${{ inputs.bundle_id }}
        INPUT_ASC_KEY_ID: ${{ inputs.asc_key_id }}
        INPUT_ASC_ISSUER_ID: ${{ inputs.asc_issuer_id }}
        INPUT_ASC_PRIVATE_KEY_B64: ${{ inputs.asc_private_key_b64 }}
        INPUT_ASC_TEAM_ID: ${{ inputs.asc_team_id }}
        INPUT_CONFIGURATION: ${{ inputs.configuration }}
        INPUT_ARCHIVE_PATH: ${{ inputs.archive_path }}
        INPUT_EXPORT_PATH: ${{ inputs.export_path }}
        INPUT_WAIT_FOR_PROCESSING: ${{ inputs.wait_for_processing }}
        INPUT_POLL_INTERVAL: ${{ inputs.poll_interval }}
        INPUT_XCODEBUILD_EXTRA_ARGS: ${{ inputs.xcodebuild_extra_args }}
