name: ReleaseKit-iOS Archive
description: Archive an iOS app and export an IPA.
author: vinceglb

inputs:
  workspace:
    description: Path to the .xcworkspace file or directory.
    required: true
  scheme:
    description: Xcode scheme to archive.
    required: true
  bundle_id:
    description: Expected app bundle identifier.
    required: true
  asc_key_id:
    description: App Store Connect API key ID.
    required: true
  asc_issuer_id:
    description: App Store Connect API issuer ID.
    required: true
  asc_private_key_b64:
    description: Base64-encoded contents of the App Store Connect private key (.p8).
    required: true
  asc_team_id:
    description: Apple Developer Team ID used for signing/export.
    required: true
  configuration:
    description: Xcode build configuration.
    required: false
    default: Release
  archive_path:
    description: Output path for generated .xcarchive.
    required: false
    default: ${{ runner.temp }}/archive/App.xcarchive
  export_path:
    description: Output directory for exported artifacts (.ipa).
    required: false
    default: ${{ runner.temp }}/export
  xcodebuild_extra_args:
    description: Additional args appended to xcodebuild archive command.
    required: false
    default: ""

outputs:
  archive_path:
    description: Absolute path to generated .xcarchive.
    value: ${{ steps.archive.outputs.archive_path }}
  ipa_path:
    description: Absolute path to generated .ipa.
    value: ${{ steps.archive.outputs.ipa_path }}
  archive_bundle_id:
    description: Bundle ID extracted from generated archive.
    value: ${{ steps.archive.outputs.archive_bundle_id }}

runs:
  using: composite
  steps:
    - name: Archive and export IPA
      id: archive
      shell: bash
      run: ${{ github.action_path }}/../../scripts/archive.sh
      env:
        INPUT_WORKSPACE: ${{ inputs.workspace }}
        INPUT_SCHEME: ${{ inputs.scheme }}
        INPUT_BUNDLE_ID: ${{ inputs.bundle_id }}
        INPUT_ASC_KEY_ID: ${{ inputs.asc_key_id }}
        INPUT_ASC_ISSUER_ID: ${{ inputs.asc_issuer_id }}
        INPUT_ASC_PRIVATE_KEY_B64: ${{ inputs.asc_private_key_b64 }}
        INPUT_ASC_TEAM_ID: ${{ inputs.asc_team_id }}
        INPUT_CONFIGURATION: ${{ inputs.configuration }}
        INPUT_ARCHIVE_PATH: ${{ inputs.archive_path }}
        INPUT_EXPORT_PATH: ${{ inputs.export_path }}
        INPUT_XCODEBUILD_EXTRA_ARGS: ${{ inputs.xcodebuild_extra_args }}
